web/main/routes.py
from flask import g, get_flashed_messages, stream_template, Blueprint, flash, request, jsonify
from flask_login import current_user, login_required
from sqlalchemy import func
import traceback
from datetime import datetime, date, timedelta

from web.models import (
    User, 
)

from web import db, csrf

from web.utils.db_session_management import db_session_management
from web.utils.decorators import role_required

main = Blueprint('main', __name__)

@main.route("/")
@login_required
# @role_required('*')
# @db_session_management
def index():
    user = User.query.filter(User.username==current_user.username).first_or_404()
    return stream_template('index.html')

@main.route("/users")
@role_required('admin')
def users():
    return stream_template('users/users.html')

@main.route("/maintainance")
def maintainance():
    return stream_template('maintainance.html')

web/templates/incs/alerts.html
{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    {% for category, msg in messages %} 

    <div class="alert text-white bg-{{ category }}" role="alert">
      <div class="iq-alert-icon">
         <i class="ri-alert-line"></i>
      </div>
      <div class="iq-alert-text">{{ msg }}</div>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <i class="ri-close-line"></i>
      </button>
   </div>

    {% endfor %}
  {% endif %}
{% endwith %} 

web/templates/incs/bottom_js.bk.html
<script src="{{url_for('static', filename='js/backend-bundle.min.js')}}"></script>
<!-- Table Treeview JavaScript -->
<script src="{{url_for('static', filename='js/table-treeview.js')}}"></script>
<!-- Chart Custom JavaScript -->
<script src="{{url_for('static', filename='js/customizer.js')}}"></script>
<!-- Chart Custom JavaScript -->
<script async src="{{url_for('static', filename='js/chart-custom.js')}}"></script>
<!-- app JavaScript -->
<script src="{{url_for('static', filename='js/app.js')}}"></script>

<script>
    switchtab = () => { $('#pills-generate-tab').trigger('click'); }
    switchtab1 = () => { $('#pills-expenses-tab').trigger('click'); }

    //set csr token in every ajax requests once here to avoid bad request-error(s)
    var csrf_token = "{{ csrf_token() }}"; // get the token from the template
    $.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
        xhr.setRequestHeader('X-CSRFToken', csrf_token); // set the header with the token
        }
    }
    });

    // notification.js
    document.addEventListener('DOMContentLoaded', function() {
        const badgeCount = document.getElementById('badge-count');
        const notificationList = document.getElementById('notification-list');
        const notificationDropdown = document.getElementById('notification-dropdown');

        function updateBadge(count) {
            badgeCount.textContent = count;
            badgeCount.style.display = count > 0 ? 'inline' : 'none';
        }

        function updateDropdown(notifications) {
            notificationList.innerHTML = '';

            if (notifications.length === 0) {
                notificationList.innerHTML = '<li>No new notifications</li>';
            } else {
                notifications.forEach(notification => {
                    const li = document.createElement('li');
                    li.textContent = notification.message;
                    notificationList.appendChild(li);
                    console.log(notificationList)
                });
            }
        }

        function fetchNotifications() {
            fetch('/get_notifications/api')
                .then(response => response.json())
                .then(data => {
                    if (data){
                    updateBadge(data.notifications.length);
                    updateDropdown(data.notifications);
                    alert(JSON.stringify(data))
                    }else{
                        console.log(data.notifications)
                    }
                })
                .catch(error => {
                    console.error('Error fetching notifications:', error);
                });
        }

        fetchNotifications();
        setInterval(fetchNotifications, 60000); // Fetch notifications every minute (adjust as needed)
    });

</script>

web/templates/incs/bottom_js.html
    <!-- Core JS -->
    <!-- build:js assets/vendor/js/core.js -->
    <script src="./static/vendor/libs/jquery/jquery.js"></script>
    <script src="./static/vendor/libs/popper/popper.js"></script>
    <script src="./static/vendor/js/bootstrap.js"></script>
    <script src="./static/vendor/libs/perfect-scrollbar/perfect-scrollbar.js"></script>

    <script src="./static/vendor/js/menu.js"></script>
    <script src="./static/js/apexcharts.js"></script>
    <script src="./static/js/total_balance_chart.js"></script>
    <!-- endbuild -->

    <!-- Vendors JS -->
    <script src="./static/vendor/libs/masonry/masonry.js"></script>

    <!-- Main JS -->
    <script src="./static/js/main.js"></script>

    <!-- Page JS -->

    <!-- Place this tag in your head or just before your close body tag. -->
    <script async defer src="https://buttons.github.io/buttons.js"></script>

web/templates/incs/cert.html
<div class="modal fade" id="certifieModal" tabindex="-1" aria-hidden="true"
                            style="display: none;">
                            <div class="modal-dialog modal-dialog-centered modal-simple modal-add-new-cc">
                                <div class="modal-content p-3 p-md-5">
                                    <div class="modal-body">
                                        <button type="button" class="btn-close" data-bs-dismiss="modal"
                                            aria-label="Close"></button>
                                        <div class="text-center mb-4">
                                            <h3>Film supply is certified</h3>
                                        </div>
                                        <div class="col-md-12">
                                            <div class="card bg-dark text-white text-center mb-3" style="width: 100%;">
                                                <img src="./static/img/cert/cert.jpg" style="width: 100%; height: auto;"
                                                    class="card-img-top" />
                                                <div class="card-img-overlay"></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

web/templates/incs/membership.html
<div class="modal fade" id="membershipModal" tabindex="-1" style="display: none;" aria-hidden="true">
    <div class="modal-dialog modal-xl modal-simple modal-pricing">
        <div class="modal-content p-0 p-md-2 p-xl-5">
            <div class="modal-body px-2 px-md-4">
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                <!-- Pricing Plans -->
                <div class="rounded-top">
                    <h2 class="text-center mb-2 mt-0 mt-md-4 px-2">Find the right plan for
                        yourself</h2>
                    <p class="text-center pb-3 px-2">
                        Choose th right plan and keep making money </p>
                    <div class="row mx-0 gy-3">
                        <!-- Basic -->
                        <div class="col-lg mb-md-0 mb-4">
                            <div class="card border rounded shadow-none">
                                <div class="card-body position-relative">
                                    <div class="my-3 pt-2 text-center">
                                        <img src="./static/img/icons/normal.png" alt="Starter Image" height="80">
                                    </div>
                                    <h3 class="card-title text-center text-capitalize mb-1">
                                        Normal</h3>
                                    <ul class="list-group my-4 list-unstyled">
                                        <li class="mb-2 d-flex align-items-center"><span
                                                class="badge badge-center w-px-20 h-px-20 rounded-pill bg-label-primary me-2"><i
                                                    class="bx bx-check bx-xs"></i></span><span>Deposit
                                                in accordance with our renewal event</span></li>
                                        <li class="mb-2 d-flex align-items-center"><span
                                                class="badge badge-center w-px-20 h-px-20 rounded-pill bg-label-primary me-2"><i
                                                    class="bx bx-check bx-xs"></i></span><span>Profit
                                                of 0.7% per order - 33 orders per set</span>
                                        </li>
                                        <li class="mb-2 d-flex align-items-center"><span
                                                class="badge badge-center w-px-20 h-px-20 rounded-pill bg-label-primary me-2"><i
                                                    class="bx bx-check bx-xs"></i></span><span>Better
                                                Profit and permission</span></li>
                                        <li class="mb-2 d-flex align-items-center"><span
                                                class="badge badge-center w-px-20 h-px-20 rounded-pill bg-label-primary me-2"><i
                                                    class="bx bx-check bx-xs"></i></span><span>Profit
                                                of 7% for each Premium Tickets</span></li>
                                        <li class="mb-2 d-flex align-items-center"><span
                                                class="badge badge-center w-px-20 h-px-20 rounded-pill bg-label-primary me-2"><i
                                                    class="bx bx-check bx-xs"></i></span><span>No
                                                access to other stage</span></li>
                                    </ul>
                                    <button type="button" class="btn btn-label-primary d-grid w-100"
                                        data-bs-dismiss="modal">Upgrade</button>

                                </div>
                            </div>
                        </div>

                        <!-- Pro -->
                        <div class="col-lg mb-md-0 mb-4">
                            <div class="card border-primary border shadow-none">
                                <div class="card-body position-relative">
                                    <div class="position-absolute end-0 me-4 top-0 mt-4">
                                        <span class="badge bg-label-primary">current</span>
                                    </div>
                                    <div class="my-3 pt-2 text-center">
                                        <img src="./static/img/icons/vip.png" alt="Pro Image" height="80">
                                    </div>
                                    <h3 class="card-title text-center text-warning text-capitalize mb-1">
                                        VIP</h3>

                                    <ul class="list-group my-4 list-unstyled">
                                        <li class="mb-2 d-flex align-items-center"><span
                                                class="badge badge-center w-px-20 h-px-20 rounded-pill bg-label-primary me-2"><i
                                                    class="bx bx-check bx-xs"></i></span><span>Deposit
                                                in accordance with our renewal event</span></li>
                                        <li class="mb-2 d-flex align-items-center"><span
                                                class="badge badge-center w-px-20 h-px-20 rounded-pill bg-label-primary me-2"><i
                                                    class="bx bx-check bx-xs"></i></span><span>Profit
                                                of 0.9% per order - 35 orders per set</span>
                                        </li>
                                        <li class="mb-2 d-flex align-items-center"><span
                                                class="badge badge-center w-px-20 h-px-20 rounded-pill bg-label-primary me-2"><i
                                                    class="bx bx-check bx-xs"></i></span><span>Better
                                                Profit and permission</span></li>
                                        <li class="mb-2 d-flex align-items-center"><span
                                                class="badge badge-center w-px-20 h-px-20 rounded-pill bg-label-primary me-2"><i
                                                    class="bx bx-check bx-xs"></i></span><span>Profit
                                                of 7% for each Premium Tickets</span></li>
                                    </ul>
                                    <button type="button" class="btn btn-label-primary d-grid w-100"
                                        data-bs-dismiss="modal">Upgrade Higher</button>
                                </div>
                            </div>
                        </div>

                        <!-- vvip -->
                        <div class="col-lg">
                            <div class="card border rounded shadow-none">
                                <div class="card-body">

                                    <div class="my-3 pt-2 text-center">
                                        <img src="./static/img/icons/vvip.png" alt="Pro Image" height="80">
                                    </div>
                                    <h3 class="card-title text-center text-capitalize mb-1">VVIP
                                    </h3>

                                    <ul class="list-group my-4 list-unstyled">
                                        <li class="mb-2 d-flex align-items-center"><span
                                                class="badge badge-center w-px-20 h-px-20 rounded-pill bg-label-primary me-2"><i
                                                    class="bx bx-check bx-xs"></i></span><span>Deposit
                                                in accordance with our renewal event</span></li>
                                        <li class="mb-2 d-flex align-items-center"><span
                                                class="badge badge-center w-px-20 h-px-20 rounded-pill bg-label-primary me-2"><i
                                                    class="bx bx-check bx-xs"></i></span><span>Profit
                                                of 1.5% per order - 38 orders per set</span>
                                        </li>
                                        <li class="mb-2 d-flex align-items-center"><span
                                                class="badge badge-center w-px-20 h-px-20 rounded-pill bg-label-primary me-2"><i
                                                    class="bx bx-check bx-xs"></i></span><span>Better
                                                Profit and permission</span></li>
                                        <li class="mb-2 d-flex align-items-center"><span
                                                class="badge badge-center w-px-20 h-px-20 rounded-pill bg-label-primary me-2"><i
                                                    class="bx bx-check bx-xs"></i></span><span>Profit
                                                of 9% for each Premium Tickets</span></li>
                                    </ul>

                                    <button type="button" class="btn btn-label-primary d-grid w-100"
                                        data-bs-dismiss="modal">Upgrade</button>
                                </div>
                            </div>
                        </div>

                        <!-- vvvip -->
                        <div class="col-lg">
                            <div class="card border rounded shadow-none">
                                <div class="card-body">

                                    <div class="my-3 pt-2 text-center">
                                        <img src="./static/img/icons/vvvip.png" alt="Pro Image" height="80">
                                    </div>
                                    <h3 class="card-title text-center text-capitalize mb-1">
                                        V.V.V.I.P</h3>

                                    <ul class="list-group my-4 list-unstyled">
                                        <li class="mb-2 d-flex align-items-center"><span
                                                class="badge badge-center w-px-20 h-px-20 rounded-pill bg-label-primary me-2"><i
                                                    class="bx bx-check bx-xs"></i></span><span>Deposit
                                                in accordance with our renewal event</span></li>
                                        <li class="mb-2 d-flex align-items-center"><span
                                                class="badge badge-center w-px-20 h-px-20 rounded-pill bg-label-primary me-2"><i
                                                    class="bx bx-check bx-xs"></i></span><span>Profit
                                                of 2% per order - 40 orders per set</span></li>
                                        <li class="mb-2 d-flex align-items-center"><span
                                                class="badge badge-center w-px-20 h-px-20 rounded-pill bg-label-primary me-2"><i
                                                    class="bx bx-check bx-xs"></i></span><span>Better
                                                Profit and permission</span></li>
                                        <li class="mb-2 d-flex align-items-center"><span
                                                class="badge badge-center w-px-20 h-px-20 rounded-pill bg-label-primary me-2"><i
                                                    class="bx bx-check bx-xs"></i></span><span>Profit
                                                of 12% for each Premium Tickets</span></li>
                                    </ul>

                                    <button type="button" class="btn btn-label-primary d-grid w-100"
                                        data-bs-dismiss="modal">Upgrade</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--/ Pricing Plans -->
        </div>
    </div>
</div>

web/templates/incs/metas.html
<meta charset="utf-8" />
<meta name="viewport"
  content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0" />
<title>Film Supply.</title>
<meta name="description" content="" />
<!-- Favicon -->
<link rel="icon" type="image/x-icon" href="./static/img/favicon/favicon.png" />
<!-- Fonts -->
<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link
  href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
  rel="stylesheet" />
<!-- Icons. Uncomment required icon fonts -->
<link rel="stylesheet" href="./static/vendor/fonts/boxicons.css" />
<!-- Core CSS -->
<link rel="stylesheet" href="./static/vendor/css/core.css" class="template-customizer-core-css" />
<link rel="stylesheet" href="./static/vendor/css/theme-default.css" class="template-customizer-theme-css" />
<link rel="stylesheet" href="./static/css/demo.css" />
<link rel="stylesheet" href="./static/css/core-dark.css" />
<!-- Vendors CSS -->
<link rel="stylesheet" href="./static/vendor/libs/perfect-scrollbar/perfect-scrollbar.css" />
<!-- Page CSS -->
<!-- Helpers -->
<script src="./static/vendor/js/helpers.js"></script>
<!--! customizer & Theme config files MUST be included after core stylesheets and helpers.js in the <head> section -->
<!--? Config:  Mandatory theme config file contain global vars & default theme options, Set your preferred theme option in this file.  -->
<script src="./static/js/config.js"></script>

web/templates/incs/modal.html
            <div class="modal fade" id="edit-note" tabindex="-1" role="dialog" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-body">
                            <div class="popup text-left">
                                <div class="media align-items-top justify-content-between">
                                    <h3 class="mb-3">Product</h3>
                                    <div class="btn-cancel p-0" data-dismiss="modal"><i class="las la-times"></i></div>
                                </div>
                                <div class="content edit-notes">
                                    <div class="card card-transparent card-block card-stretch event-note mb-0">
                                        <div class="card-body px-0 bukmark">
                                            <div
                                                class="d-flex align-items-center justify-content-between pb-2 mb-3 border-bottom">
                                                <div class="quill-tool">
                                                </div>
                                            </div>
                                            <div id="quill-toolbar1">
                                                <p>
                                                    Hi my name is Chris James.
                                                    Elite software developer with special interest in artificial intelligence, business intelligence & data.
                                                </p>
                                            </div>
                                        </div>
                                        <div class="card-footer border-0">
                                            <div class="d-flex flex-wrap align-items-ceter justify-content-end">
                                                <div class="btn btn-primary mr-3" data-dismiss="modal">Cancel</div>
                                                <div class="btn btn-outline-primary" data-dismiss="modal">Save</div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

web/templates/incs/sidenav.html
<div class="iq-sidebar  sidebar-default ">
    <div class="iq-sidebar-logo d-flex align-items-center justify-content-between">
        <a href="/" class="header-logo">
            <img src="{{url_for('static', filename='images/logo/favicon.png')}}" class="img-fluid rounded-normal light-logo" alt="logo">
            <h5 class="logo-title light-logo ml-3">D.Academy</h5>
        </a>
        <div class="iq-menu-bt-sidebar ml-0" style="cursor:pointer">
            <i class="las la-bars wrapper-menu"></i>
        </div>
    </div>
    <div class="data-scrollbar" data-scroll="1" data-scrollbar="true" tabindex="-1"
        style="overflow: hidden; outline: none;">
        <div class="scroll-content">
            <nav class="iq-sidebar-menu">
                <ul id="iq-sidebar-toggle" class="iq-menu">
                    <li class="{% if is_active('main.index')  %}active text-warning{% endif %}">
                        <a href="/" class="svg-icon">
                            <svg class="svg-icon" id="p-dash1" width="20" height="20" xmlns="http://www.w3.org/2000/svg"
                                viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"
                                stroke-linecap="round" stroke-linejoin="round">
                                <path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z">
                                </path>
                                <polyline points="3.27 6.96 12 12.01 20.73 6.96"></polyline>
                                <line x1="12" y1="22.08" x2="12" y2="12"></line>
                            </svg>
                            <span class="ml-4">Overview</span>
                        </a>
                    </li>

                    <li class="{% if is_active('auth.update') %} active text-warning {% endif %}">
                        <a href="{{url_for('auth.update', username=current_user.username)}}">
                            <svg class="svg-icon" id="p-dash3" width="20" height="20" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect>
                                <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path>
                            </svg>
                            <span class="ml-4">My Account</span>
                        </a>
                    </li>

                    <li class="{% if is_active('auth.users') %} active text-warning {% endif %}">
                        <a href="{{url_for('main.users')}}">
                            <svg class="svg-icon" id="p-dash8" width="20" height="20" xmlns="http://www.w3.org/2000/svg"
                                viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"
                                stroke-linecap="round" stroke-linejoin="round">
                                <path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path>
                                <circle cx="9" cy="7" r="4"></circle>
                                <path d="M23 21v-2a4 4 0 0 0-3-3.87"></path>
                                <path d="M16 3.13a4 4 0 0 1 0 7.75"></path>
                            </svg>
                            <span class="ml-4">Users</span>
                            <svg class="svg-icon iq-arrow-right arrow-active" width="20" height="20"
                                xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                                stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                                <polyline points="10 15 15 20 20 15"></polyline>
                                <path d="M4 4h7a4 4 0 0 1 4 4v12"></path>
                            </svg>
                        </a>
                    </li>

                    <li>
                        <button class="btn" data-toggle="modal" 
                        data-target="#attendance_moal">
                            <svg class="svg-icon" id="p-dash8" width="20" height="20" 
                            xmlns="http://www.w3.org/2000/svg"
                                viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"
                                stroke-linecap="round" stroke-linejoin="round">
                                <path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path>
                                <circle cx="9" cy="7" r="4"></circle>
                                <path d="M23 21v-2a4 4 0 0 0-3-3.87"></path>
                                <path d="M16 3.13a4 4 0 0 1 0 7.75"></path>
                            </svg>
                            <span class="ml-4">Attendance</span>
                        </button>

                    </li>

                </ul>
            </nav>
            <div id="sidebar-bottom" class="position-relative sidebar-bottom">
                <div class="card border-none">
                    <div class="card-body p-0">
                        <div class="sidebarbottom-content">
                            <div class="image"><img src="{{url_for('static', filename='images/layouts/side-bkg.png')}}" class="img-fluid"
                                    alt="side-bkg"></div>
                            <h6 class="mt-4 px-4 body-title">Being curious...?</h6>
                            <a href="https://dunistech.ng" class="btn sidebar-bottom-btn mt-4">Go to weebsite</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="p-3"></div>
        </div>
        <div class="scrollbar-track scrollbar-track-x" style="display: none;">
            <div class="scrollbar-thumb scrollbar-thumb-x" style="width: 260px; transform: translate3d(0px, 0px, 0px);">
            </div>
        </div>
        <div class="scrollbar-track scrollbar-track-y" style="display: block;">
            <div class="scrollbar-thumb scrollbar-thumb-y"
                style="height: 986.513px; transform: translate3d(0px, 0px, 0px);"></div>
        </div>
    </div>
</div>